In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [41]:
df= pd.read_csv('tuyensinh10TpHue.csv', encoding='utf-8')

In [42]:
df.head()

,SBD,Họ và tên,Giới tính,Ngày sinh,Trường TH/THCS,Quận/Huyện/TX,Nguyện vọng 1,Nguyện vọng 2,Nguyện vọng 3,Điểm Toán,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,10197,NGÔ THỊ MINH ANH,x,7/8/2010,THCS thị trấn Khe Tre,Huyện Phú Lộc,THPT Nam Đông,THPT Phú Lộc,NaN,"6,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10198,HỒ THỊ NGỌC ANH,x,15/08/2010,THCS Tố Hữu,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Gia Hội,THPT Bùi Thị Xuân,"6,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10199,LÊ THỊ NGỌC ANH,x,18/07/2010,THCS Đặng Văn Ngữ,Quận Thuận Hóa,THPT Hai Bà Trưng,THPT Nguyễn Trường Tộ,THPT Gia Hội,"5,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10200,MAI THỊ NGỌC ANH,x,11/5/2010,THCS Lê Hồng Phong,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Cao Thắng,THPT Bùi Thị Xuân,"5,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10201,NGUYỄN THỊ NGỌC ANH,x,25/07/2010,THCS Nguyễn Cư Trinh,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Đặng Huy Trứ,THPT Hương Vinh,"4,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# Kiểm tra các dòng giống hệt nhau
duplicated_rows = df[df.duplicated()]
print(f"Số dòng trùng lặp hoàn toàn: {duplicated_rows.shape[0]}")
df = df.drop_duplicates()

Số dòng trùng lặp hoàn toàn: 122

In [44]:
from unidecode import unidecode

df.columns = [unidecode(col).lower().replace(" ", "_") for col in df.columns]

In [45]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,...,unnamed:_17,unnamed:_18,unnamed:_19,unnamed:_20,unnamed:_21,unnamed:_22,unnamed:_23,unnamed:_24,unnamed:_25,unnamed:_26
0,10197,NGÔ THỊ MINH ANH,x,7/8/2010,THCS thị trấn Khe Tre,Huyện Phú Lộc,THPT Nam Đông,THPT Phú Lộc,NaN,"6,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10198,HỒ THỊ NGỌC ANH,x,15/08/2010,THCS Tố Hữu,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Gia Hội,THPT Bùi Thị Xuân,"6,25",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10199,LÊ THỊ NGỌC ANH,x,18/07/2010,THCS Đặng Văn Ngữ,Quận Thuận Hóa,THPT Hai Bà Trưng,THPT Nguyễn Trường Tộ,THPT Gia Hội,"5,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10200,MAI THỊ NGỌC ANH,x,11/5/2010,THCS Lê Hồng Phong,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Cao Thắng,THPT Bùi Thị Xuân,"5,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10201,NGUYỄN THỊ NGỌC ANH,x,25/07/2010,THCS Nguyễn Cư Trinh,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Đặng Huy Trứ,THPT Hương Vinh,"4,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df.isnull().sum()

sbd                           0
ho_va_ten                     0
gioi_tinh                  3521
ngay_sinh                     0
truong_th/thcs                1
quan/huyen/tx                 1
nguyen_vong_1                70
nguyen_vong_2               231
nguyen_vong_3              1364
diem_toan                   149
diem_ngu_van/tieng_viet     147
diem_ngoai_ngu              148
tong_xet_pho_thong/ntp      149
ket_qua                       1
unnamed:_14                6908
unnamed:_15                6908
unnamed:_16                6908
unnamed:_17                6908
unnamed:_18                6908
unnamed:_19                6908
unnamed:_20                6908
unnamed:_21                6909
unnamed:_22                6908
unnamed:_23                6908
unnamed:_24                6908
unnamed:_25                6908
unnamed:_26                6908
dtype: int64

In [47]:
df=df.drop(columns=['unnamed:_14', 'unnamed:_15', 'unnamed:_16', 'unnamed:_17', 
'unnamed:_18', 'unnamed:_19', 'unnamed:_20', 'unnamed:_21', 'unnamed:_22',
 'unnamed:_23', 'unnamed:_24', 'unnamed:_25', 'unnamed:_26'])

In [48]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,tong_xet_pho_thong/ntp,ket_qua
0,10197,NGÔ THỊ MINH ANH,x,7/8/2010,THCS thị trấn Khe Tre,Huyện Phú Lộc,THPT Nam Đông,THPT Phú Lộc,NaN,"6,25","8,50","9,4","34,15",Đậu Trường THPT Nam Đông
1,10198,HỒ THỊ NGỌC ANH,x,15/08/2010,THCS Tố Hữu,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Gia Hội,THPT Bùi Thị Xuân,"6,25","8,00","6,8","31,05",Đậu Trường THPT Nguyễn Huệ
2,10199,LÊ THỊ NGỌC ANH,x,18/07/2010,THCS Đặng Văn Ngữ,Quận Thuận Hóa,THPT Hai Bà Trưng,THPT Nguyễn Trường Tộ,THPT Gia Hội,"5,50","7,00","7,8","30,3",Đậu Trường THPT Nguyễn Trường Tộ
3,10200,MAI THỊ NGỌC ANH,x,11/5/2010,THCS Lê Hồng Phong,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Cao Thắng,THPT Bùi Thị Xuân,"5,50","6,50",9,"30,0",Đậu Trường THPT Nguyễn Huệ
4,10201,NGUYỄN THỊ NGỌC ANH,x,25/07/2010,THCS Nguyễn Cư Trinh,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Đặng Huy Trứ,THPT Hương Vinh,"4,00","8,00","6,4","28,4",Đậu Trường THPT Nguyễn Huệ

In [49]:
cols_diem = ['diem_toan', 'diem_ngu_van/tieng_viet', 'diem_ngoai_ngu', 'tong_xet_pho_thong/ntp']

for col in cols_diem:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')  # chuyển sang float, lỗi thì thành NaN

In [50]:
df['diem_THCS']=(df['tong_xet_pho_thong/ntp']- df['diem_ngoai_ngu']- df['diem_ngu_van/tieng_viet']-df['diem_toan'])

In [51]:
df.head()

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,tong_xet_pho_thong/ntp,ket_qua,diem_THCS
0,10197,NGÔ THỊ MINH ANH,x,7/8/2010,THCS thị trấn Khe Tre,Huyện Phú Lộc,THPT Nam Đông,THPT Phú Lộc,NaN,6.25,8.5,9.4,34.15,Đậu Trường THPT Nam Đông,10.0
1,10198,HỒ THỊ NGỌC ANH,x,15/08/2010,THCS Tố Hữu,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Gia Hội,THPT Bùi Thị Xuân,6.25,8.0,6.8,31.05,Đậu Trường THPT Nguyễn Huệ,10.0
2,10199,LÊ THỊ NGỌC ANH,x,18/07/2010,THCS Đặng Văn Ngữ,Quận Thuận Hóa,THPT Hai Bà Trưng,THPT Nguyễn Trường Tộ,THPT Gia Hội,5.50,7.0,7.8,30.30,Đậu Trường THPT Nguyễn Trường Tộ,10.0
3,10200,MAI THỊ NGỌC ANH,x,11/5/2010,THCS Lê Hồng Phong,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Cao Thắng,THPT Bùi Thị Xuân,5.50,6.5,9.0,30.00,Đậu Trường THPT Nguyễn Huệ,9.0
4,10201,NGUYỄN THỊ NGỌC ANH,x,25/07/2010,THCS Nguyễn Cư Trinh,Quận Phú Xuân,THPT Nguyễn Huệ,THPT Đặng Huy Trứ,THPT Hương Vinh,4.00,8.0,6.4,28.40,Đậu Trường THPT Nguyễn Huệ,10.0

In [ ]:
df['gioi_tinh'] = df['gioi_tinh'].replace('x', 'Nữ')
df['gioi_tinh'] = df['gioi_tinh'].replace('', 'Nam')  # thay chuỗi rỗng 
df['gioi_tinh'] = df['gioi_tinh'].fillna('Nam')       # thay NaN bằng Nam

In [58]:
df.head(1)

,sbd,ho_va_ten,gioi_tinh,ngay_sinh,truong_th/thcs,quan/huyen/tx,nguyen_vong_1,nguyen_vong_2,nguyen_vong_3,diem_toan,diem_ngu_van/tieng_viet,diem_ngoai_ngu,tong_xet_pho_thong/ntp,ket_qua,diem_THCS
0,10197,NGÔ THỊ MINH ANH,Nữ,7/8/2010,THCS thị trấn Khe Tre,Huyện Phú Lộc,THPT Nam Đông,THPT Phú Lộc,NaN,6.25,8.5,9.4,34.15,Đậu Trường THPT Nam Đông,10.0

In [59]:
df['diem_THCS'] = df['diem_THCS'].fillna(0)
df['diem_toan'] = df['diem_toan'].fillna(0)
df['diem_ngoai_ngu'] = df['diem_ngoai_ngu'].fillna(0)
df['diem_ngu_van/tieng_viet'] = df['diem_ngu_van/tieng_viet'].fillna(0)
df['tong_xet_pho_thong/ntp'] = df['tong_xet_pho_thong/ntp'].fillna(0)

In [60]:
df.to_csv('tuyensinh10TpHue_cleaned.csv', index=False, encoding='utf-8-sig')